### PR TITLE
Fix for flask dependencies

### PR DESCRIPTION
**Pull request by ethgra**
Hello,

Fix for [T309862-ORES server does not start due to flask dependency conflicts](https://phabricator.wikimedia.org/T309862)

Pinning version of Jinja2 and itsdangerous to make the application launch after installations. Other choice is to upgrade flask itself but I think that is more risky.

Regards,
Ethan

### CODE REVIEW

**Comment by elukey** [comment]
Hi! What version of Flask is this change installing? We are using Flask 1.0.4 and we didn't get issues, curious about your use case.

**Comment by ethgra** [comment]
Hello,

 Thanks for taking the time to review. I have not changed the flask version so it is still - 1.0.2. Since you are not getting the issue I presume you have jinja2 < 3.0.3  and itsdangerous < 2.0.1 in your site-packages so the system will not try to install higher versions, hence no issues when you deploy. Since I was doing the changes in a virtual environment, the system downloaded the max allowed stable version and got into this issue.

The issue has been discussed [here ](https://stackoverflow.com/questions/71645272/importerror-cannot-import-name-markup-from-jinja2). I took a less risky approach to just pin the versions of the troubling packages than upgrading Flask itself.

Regards,
Ethan

**Comment by ethgra** [comment]
Hello,

 I also tried with flask 1.0.4. I was able to reproduce the error. I had to first remove the existing jinja2 and itsdangerous before pip install. As you mentioned if it is not causing any issues maybe you can ignore the pull request.

(ores_venv)      :/ores_2/ores (T309862_requirement_txt) $ pip show flask
**Name: Flask
Version: 1.0.4**
Summary: A simple framework for building complex web applications.
Home-page: https://palletsprojects.com/p/flask/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/ores_2/ores/ores_venv/lib/python3.7/site-packages
Requires: click, itsdangerous, Jinja2, Werkzeug
Required-by: Flask-Jsonpify, flask-swaggerui, flask-wikimediaui
(ores_venv)      :/ores_2/ores (T309862_requirement_txt) $ ./utility applications.wsgi
Traceback (most recent call last):
  File "/home/ores_2/ores/ores/ores.py", line 50, in main
    module = import_module(module_path, package="ores")
  File "/home/ores_2/ores/ores_venv/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ores_2/ores/ores/applications/wsgi.py", line 24, in <module>
    from ores.wsgi import server
  File "/home/ores_2/ores/ores/wsgi/server.py", line 3, in <module>
    import flask_swaggerui
  File "/home/ores_2/ores/ores_venv/lib/python3.7/site-packages/flask_swaggerui/__init__.py", line 1, in <module>
    from .functions import render_swaggerui, build_static_blueprint
  File "/home/ores_2/ores/ores_venv/lib/python3.7/site-packages/flask_swaggerui/functions.py", line 1, in <module>
    from flask import render_template_string, Blueprint, send_from_directory
  File "/home/ores_2/ores/ores_venv/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/home/ores_2/ores/ores_venv/lib/python3.7/site-packages/jinja2/__init__.py)
Could not find module .applications.wsgi.
(ores_venv)      :~/ores_2/ores (T309862_requirement_txt) $ 

Regards,
Ethan

**Comment by elukey** [comment]
I can confirm, we have jinja 2.11.3 and itsdangerous 1.1.0 in production, so this is probably why it works without issues.

**Comment by ethgra** [comment]
Happy to do it. Would you like me to update the flask version to 1.0.4 as well ?

**Comment by ethgra** [comment]
Ignore the question on Flask version. Flask 1.0.4 is the highest available version in the range specified(1.0.2, < 1.0.999) in the requirement.txt. I tried to update requirement.txt to jinja-2.11.3 and itsdangerous-1.1.0 but it fails with markupsafe lib. The default version of "markupsafe" that gets installed is 2.1.1 which we will have to change to 2.0.0 or lesser. Would you be able to check the version of  "markupsafe" in Prod and let me know? I can align that also. I am able to start the server and run all test cases with the below changes

+jinja2 == 2.11.3
+itsdangerous == 1.1.0
+markupsafe == 2.0.0

Thanks again for the support.

Regards,
Ethan

**Comment by elukey** [comment]
The Markupsafe version seems to be 1.1.1, does it work?

**Comment by ethgra** [comment]
Thanks again for supporting me. Markupsafe version 1.1.1 works well and all the 80 cases passed. Kindly review the change when time permits.

Regards,
Ethan

**Comment by elukey** [comment]
Merged, thanks a lot for your contribution!

**Pull request merged**
